### ISSUE TITLE
How to start train with local Omniboard

### ISSUE THREAD

**Issue by Neonsign247** [GoodAI/GTN#1]
Thanks for great code.

I'd like to start experiment with your code on docker enviroment.

As far as I know, I cannot use docker-compose inside docker container.

So I tried using local omniboard, (npm install -g omniboard), my code is like this:

`
omniboard -m 192.168.1.1:27017:sacred
`

And then executing experiment/mnist_experiement.py result

`
INFO - GTN mnist - Running command 'main'
ERROR - GTN mnist - Failed after 0:00:00!
ERROR - GTN mnist - Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/sacred/run.py", line 235, in __call__
    self._emit_started()
  File "/opt/conda/lib/python3.7/site-packages/sacred/run.py", line 333, in _emit_started
    _id=self._id,
  File "/opt/conda/lib/python3.7/site-packages/sacred/observers/mongo.py", line 223, in started_event
    self.run_entry["experiment"]["sources"] = self.save_sources(ex_info)
  File "/opt/conda/lib/python3.7/site-packages/sacred/observers/mongo.py", line 406, in save_sources
    file = self.fs.find_one({"filename": abs_path, "md5": md5})
  File "/opt/conda/lib/python3.7/site-packages/gridfs/__init__.py", line 302, in find_one
    for f in self.find(filter, *args, session=session, **kwargs):
  File "/opt/conda/lib/python3.7/site-packages/gridfs/grid_file.py", line 827, in next
    next_file = super(GridOutCursor, self).next()
  File "/opt/conda/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/opt/conda/lib/python3.7/site-packages/pymongo/cursor.py", line 1073, in _refresh
    self.__send_message(q)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/cursor.py", line 955, in __send_message
    address=self.__address)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
    exhaust=exhaust)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1458, in _retryable_read
    exhaust=exhaust) as (sock_info,
  File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1282, in _slaveok_for_server
    with self._get_socket(server, session, exhaust=exhaust) as sock_info:
  File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1222, in _get_socket
    self.__all_credentials, checkout=exhaust) as sock_info:
  File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/pool.py", line 1138, in get_socket
    sock_info.check_auth(all_credentials)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/pool.py", line 712, in check_auth
    auth.authenticate(credentials, self)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/auth.py", line 564, in authenticate
    auth_func(credentials, sock_info)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/auth.py", line 263, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/pool.py", line 613, in command
    user_fields=user_fields)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/network.py", line 167, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/opt/conda/lib/python3.7/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
`

I cannot get the right direction to solve the above problems.

Please help me to get through it...!

**Comment by martinpoliak-goodai** [comment]
Hi Neonsign247, let's start with the obvious stuff. You will notice that docker compose configures a mongo database with a user "sample" and password "password". I understand that you decided to skip the docker part. Did you configure your mongo installation to match what the code expects? Alternatively, use an existing mongo username/password combination and adapt the sacred_config.py script accordingly.

**Comment by Neonsign247** [comment]
Thanks for the reply. I changed some part in 'GTN/badger_utils/sacred/sacred_config.py ' and installed 'npm install -g omniboard'. And both training and omniboard works well!! However, after training, ntb_result_analyzer.py doesn't work..... I cannot get through it. Help me please!

Traceback (most recent call last):
  File "ntb_result_analyzer.py", line 136, in <module>
    data, target = generate_teacher_curriculum_images(*load_random_fixed_teacher(*run_id         _random_fixed))
  File "ntb_result_analyzer.py", line 102, in load_random_fixed_teacher
    teacher_input = reader.load_tensor('teacher_input.pt', epoch)
  File "/lhi/GTN/badger_utils/sacred/sacred_reader.py", line 72, in load_tensor
    return torch.load(self._checked_artifact_file(name, epoch))
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 526, in loa         d
    if _is_zipfile(opened_file):
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 76, in _is_         zipfile
    if ord(magic_byte) != ord(read_byte):
TypeError: ord() expected a character, but string of length 0 found

**Comment by martinpoliak-goodai** [comment]
I'd recommend running the ntb_ file also from a jupyter notebook, so you get access to interactivity. We're using the jupytext extension to synchronize between the .py and .ipynb files. The error that you are seeing is most probably caused by the fact that the script is using hardcoded ids of runs of GTN experiment. You should update the script's run_id_* variables with your actual experiment run ids.
